object Versions {
    const val kotlin = "1.8.10"
    const val lifecycle = "2.6.1"
    const val compose = "2023.03.00"
    const val composeActivity = "1.7.2"
    const val coreKtx = "1.10.1"
    const val junit = "4.13.2"
    const val retrofitSerializationConverter = "1.0.0"
    const val retrofit = "2.9.0"
    const val hilt = "2.44"
    const val kotlinSerialization = "1.5.1"
    const val room = "2.5.1"
    const val logInterceptor = "4.11.0"
    const val composeNav = "2.5.3"
    const val coil = "2.4.0"
    const val paging = "3.1.1"
    const val pagingCompose = "3.2.0"
    const val datastore = "1.0.0"
}